### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/seo-blog1#2]
Automated Review Comments
Issues in .cache/eleventy-fetch-1054bc9cae6f946842171dcfc540c8:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in .cache/eleventy-fetch-88def36f9795af72590d0d510a5866:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in .cache/eleventy-fetch-88def36f9795af72590d0d510a5866.buffer:
  - (2, 'Line exceeds 80 characters')
Issues in LICENSE:
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in dist/404.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in dist/assets/favicon/site.webmanifest:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in dist/blog/index.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in dist/blog/sample-post/index.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by Py-Ec** [comment]
I got it.
